// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CasoDeTesteAEPTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void casoDeTesteAEP() {
    driver.get("https://buildexpress.vercel.app/");
    driver.manage().window().setSize(new Dimension(812, 672));
    driver.findElement(By.cssSelector(".sc-papXJ li:nth-child(2) > button")).click();
    driver.findElement(By.cssSelector(".slick-active:nth-child(2) > button")).click();
    driver.findElement(By.cssSelector(".sc-papXJ li:nth-child(1) > button")).click();
    driver.findElement(By.cssSelector(".sc-fLlhyt li:nth-child(2) > button")).click();
    driver.findElement(By.cssSelector(".sc-fLlhyt li:nth-child(1) > button")).click();
    driver.findElement(By.cssSelector(".sc-evZas li:nth-child(2) > button")).click();
    driver.findElement(By.cssSelector(".sc-jSMfEi:nth-child(1) > svg")).click();
    driver.findElement(By.cssSelector(".sc-jSMfEi:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".sc-jSMfEi:nth-child(3) > svg")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".App"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".App"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".App"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.cssSelector(".App")).click();
    driver.findElement(By.cssSelector(".sc-bczRLJ")).click();
  }
}
